####################################
# Labels based on changed files    #
####################################
🏭 Backend Changes:
- changed-files:
  - any-glob-to-any-file:
    - "apps/server/src/**"
    - "apps/server/default/config.yaml"
    - "apps/server/server.js"
    - "apps/server/plugins.js"
    - "apps/server/recover.js"
    - "apps/server/webpack.config.js"
    - "Start.bat"
    - "start.sh"
    - "UpdateAndStart.bat"
    - "UpdateForkAndStart.bat"

⚙️ config.yaml:
- changed-files:
  - any-glob-to-any-file:
    - "apps/server/default/config.yaml"
    - "apps/server/config.yaml"

🛠️ Build Changes:
- changed-files:
  - any-glob-to-any-file:
    - ".github/workflows/**"
    - "docker/**"
    - ".dockerignore"
    - "Dockerfile"
    - "apps/server/webpack.config.js"

🌐 Language:
- changed-files:
  - any-glob-to-any-file:
    - "apps/server/public/locales/**"

📥 Dependencies:
- changed-files:
  - any-glob-to-any-file:
    - "apps/server/public/lib/**" # Every frontend lib counts as a dependency as well
    - "package.json"
    - "package-lock.json"
    - "apps/server/package.json"
    - "apps/server/package-lock.json"
    - "apps/mobile/package.json"
    - "apps/mobile/package-lock.json"
    - "apps/electron/package.json"
    - "apps/electron/package-lock.json"
    - "apps/tests/package.json"
    - "apps/tests/package-lock.json"
